import data from "@/data";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-screen-lg  mx-auto px-5">
          <div>
            <nav className=" mt-20">
              <h1>List of items</h1>
              <div className="flex flex-col gap-5">
                {data?.map((item) => (
                  <Link key={item.id} href={`${item.id}`}>
                    <button className="border p-3 w-36 rounded-lg">
                      {item.name}
                    </button>
                  </Link>
                ))}
              </div>
            </nav>
            <div className="">{children}</div>
          </div>
        </div>

        {/* <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-1/2 text-center ">
        </div> */}
      </body>
    </html>
  );
}
